- num_optimizations: 2
  initial_guess: ""
  spine_type: twisting
  urdf_path: examples/Spirit_spine/spirit_with_spine_drake.urdf
  saved_directory: /home/feng/Downloads/dairlib/examples/Spirit_spine/saved_trajectories/parkour_wall_jump_test3/
  iterate: ~
  num_perturbations: 10
  mean: 1
  var: 0.01
- name: parkour_pronk_1
  n_jumps: 2
  transition_surface:
    -
      - 0
      - 0
      - 1
      - 0
      - 0
      - 0.3
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 4
  apex_heights:
    - 0.7
    - 0.7
  max_pitch_magnitude: 0.6
  max_apex_pitch_magnitude: 0.1
  pose_ref: false
  roll_ref: 0.3
  yaw_ref: 0.1
  pitch_ref: 0.3
  max_duration: 4
  cost_actuation: 3
  cost_velocity: 10
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0
  mu: 100
  eps: 5e-2
  tol: 10
  xtol: 1e-2
  file_name_out: simple_parkour_2_1
  file_name_in: ""
  animate: false
- name: parkour_pronk_2
  n_jumps: 2
  transition_surface:
    -
      - 0
      - 0.4
      - 0.8
      - 0
      - -0.1
      - 0.35
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 4
  apex_heights:
    - 0.65
    - 0.65
  max_pitch_magnitude: 0.6
  max_apex_pitch_magnitude: 0.1
  pose_ref: true
  roll_ref: 0.2
  yaw_ref: 0.1
  pitch_ref: 0.3
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0
  mu: 100
  eps: 1e-2
  tol: 1e1
  xtol: 1e-2
  file_name_out: simple_parkour_2_2
  file_name_in: simple_parkour_2_1
  animate: false
- name: parkour_pronk_3
  n_jumps: 2
  transition_surface:
    -
      - 0
      - 0.8
      - 0.3
      - 0
      - -0.2
      - 0.35
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 4
  apex_heights:
    - 0.65
    - 0.65
  max_pitch_magnitude: 0.6
  max_apex_pitch_magnitude: 0.1
  pose_ref: false
  roll_ref: 0.3
  yaw_ref: 0.1
  pitch_ref: 0.3
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0
  mu: 10
  eps: 1e-2
  tol: 1
  xtol: 1e-2
  file_name_out: simple_parkour_2_3
  file_name_in: simple_parkour_2_2
  animate: false
- name: parkour_pronk_4
  n_jumps: 2
  transition_surface:
    -
      - 0
      - 0.8
      - 0.3
      - 0.7
      - -0.2
      - 0.35
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 1.4
    - 0
    - 0
    - false
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 4
  apex_heights:
    - 0.65
    - 0.65
  max_pitch_magnitude: 0.6
  max_apex_pitch_magnitude: 0.1
  pose_ref: true
  roll_ref: 1
  yaw_ref: 0.5
  pitch_ref: 0.6
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0
  mu: 10
  eps: 1e-2
  tol: 1e2
  xtol: 1e-2
  file_name_out: simple_parkour_2_4
  file_name_in: simple_parkour_2_3
  animate: false
- name: parkour_pronk_5
  n_jumps: 2
  transition_surface:
    -
      - 0
      - 0.8
      - 0.3
      - 0.7
      - -0.25
      - 0.35
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 1.5
    - 0
    - 0
    - false
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 4
  apex_heights:
    - 0.65
    - 0.65
  max_pitch_magnitude: 1.2
  max_apex_pitch_magnitude: 0.1
  pose_ref: true
  roll_ref: 1
  yaw_ref: 0.6
  pitch_ref: 0.6
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0
  mu: 10
  eps: 1e-2
  tol: 1
  xtol: 5e-2
  file_name_out: simple_parkour_2_5
  file_name_in: simple_parkour_2_4
  animate: false
- name: parkour_pronk_7
  warm_up: true
  n_jumps: 2
  transition_surface:
    -
      - 0
      - 1
      - 0
      - 0.7
      - -0.6
      - 0.65
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 1.5
    - 0.05
    - 0
    - false
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 4
  apex_heights:
    - 0.65
    - 0.65
  max_pitch_magnitude: 1.2
  max_apex_pitch_magnitude: 0.1
  pose_ref: true
  roll_ref: 1.5
  yaw_ref: 0.3
  pitch_ref: 1
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0
  mu: 1
  eps: 1e-2
  tol: 1e-1
  xtol: 5e-2
  file_name_out: simple_parkour_2_7
  file_name_in: simple_parkour_2_5
  animate: false
- name: parkour_pronk_8
  warm_up: false
  n_jumps: 2
  transition_surface:
    -
      - 0
      - 1
      - 0
      - 0.7
      - -0.6
      - 0.65
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 1.5
    - 0
    - 0
    - false
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 4
  apex_heights:
    - 0.65
    - 0.65
  max_pitch_magnitude: 1.2
  max_apex_pitch_magnitude: 0.1
  pose_ref: true
  roll_ref: 1.6
  yaw_ref: 0.7
  pitch_ref: 1
  max_duration: 2
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 10
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_work: 100
  mu: 1
  eps: 1e-2
  tol: 1
  xtol: 5e-2
  file_name_out: simple_parkour_2_8
  file_name_in: simple_parkour_2_7
  animate: false