- num_optimizations: 2
  initial_guess: ""
  saved_directory: /home/feng/Downloads/dairlib/examples/Spirit/saved_trajectories/parkour_jump_test1/
  iterate: ~
- name: parkour_pronk_1
  n_jumps: 2
  transition_surface:
    -
      - 0
      - 0
      - 1
      - 0
      - 0
      - 0.3
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 7
  apex_height: 0.65
  max_pitch_magnitude: 0.6
  max_apex_pitch_magnitude: 0.1
  lock_rotation: true
  lock_legs_apex: false
  force_symmetry: true
  max_duration: 4
  cost_actuation: 3
  cost_velocity: 10
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0
  mu: 100
  eps: 5e-2
  tol: 1e-1
  work_constraint_scale: 0
  file_name_out: simple_parkour_2_1
  file_name_in: ""
  animate: false
- name: parkour_pronk_2
  n_jumps: 2
  transition_surface:
    -
      - 0
      - 0.2
      - 1
      - 0
      - 0
      - 0.3
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 7
  apex_height: 0.65
  max_pitch_magnitude: 0.6
  max_apex_pitch_magnitude: 0.1
  lock_rotation: true
  lock_legs_apex: false
  force_symmetry: true
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0
  mu: 100
  eps: 5e-2
  tol: 1e+1
  work_constraint_scale: 0
  file_name_out: simple_parkour_2_2
  file_name_in: simple_parkour_2_1
  animate: false
- name: parkour_pronk_3
  n_jumps: 2
  transition_surface:
    -
      - 0
      - 0.4
      - 0.8
      - 0
      - 0
      - 0.35
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 7
  apex_height: 0.65
  max_pitch_magnitude: 0.6
  max_apex_pitch_magnitude: 0.1
  lock_rotation: true
  lock_legs_apex: false
  force_symmetry: false
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0
  mu: 100
  eps: 5e-2
  tol: 1e+1
  work_constraint_scale: 0
  file_name_out: simple_parkour_2_3
  file_name_in: simple_parkour_2_2
  animate: false
- name: parkour_pronk_4
  n_jumps: 2
  transition_surface:
    -
      - 0
      - 0.4
      - 0.8
      - 0
      - 0
      - 0.35
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 7
  apex_height: 0.65
  max_pitch_magnitude: 0.6
  max_apex_pitch_magnitude: 0.1
  lock_rotation: true
  lock_legs_apex: false
  force_symmetry: false
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0
  mu: 1
  eps: 5e-2
  tol: 1e+1
  work_constraint_scale: 0
  file_name_out: simple_parkour_2_4
  file_name_in: simple_parkour_2_3
  animate: false