- num_optimizations: 2
  initial_guess: ""
  saved_directory: /home/feng/Downloads/dairlib/examples/Spirit/saved_trajectories/parkour_jump_test1/
  iterate: ~
- name: parkour_jump_1
  n_jumps: 2
  transition_surface:
    - 0
    - 1
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 7
  apex_height: 0.5
  lock_rotation: true
  lock_legs_apex: true
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 15
  cost_work: 0
  mu: 100
  eps: 1e-2
  tol: 1e-1
  work_constraint_scale: 0
  file_name_out: simple_parkour_2_1
  file_name_in: ""
  animate: true