- num_optimizations: 1
  initial_guess: ""
  saved_directory: /home/feng/Downloads/dairlib/examples/Spirit_spine/saved_trajectories/bound_gait/
  spine_type: twisting
  urdf_path: examples/Spirit_spine/spirit_with_spine_drake.urdf
- name: bound_1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.35
  pitch_magnitude_lo: 0.1
  pitch_magnitude_apex: 0.1
  lock_spine: true
  apex_height: 0.4
  speed: 0
  max_duration: 1
  lock_leg_apex: true
  cost_actuation: 3
  cost_velocity: 10
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0
  mu: 100
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait1
  file_name_in: ""
- name: bound_2
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  pitch_magnitude_lo: 0.1
  pitch_magnitude_apex: 0.0001
  lock_spine: true
  apex_height: 0.4
  speed: 0
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 3
  cost_velocity: 10
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait2
  file_name_in: bounding_gait1
- name: bound_3
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  pitch_magnitude_lo: 0.1
  pitch_magnitude_apex: 0.01
  lock_spine: true
  apex_height: 0.4
  speed: 0.3
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 3
  cost_velocity: 10
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 0
  cost_work: 0
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait3
  file_name_in: bounding_gait2
- name: bound_4
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  pitch_magnitude_lo: 0.1
  pitch_magnitude_apex: 0.03
  lock_spine: true
  apex_height: -1
  speed: 0.6
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 3
  cost_velocity: 10
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 0
  cost_work: 0
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait4
  file_name_in: bounding_gait3
- name: bound_5
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  pitch_magnitude_lo: 0.2
  pitch_magnitude_apex: 0.1
  lock_spine: true
  apex_height: -1
  speed: 1
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_work: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait5
  file_name_in: bounding_gait4
- name: bound_6
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  pitch_magnitude_lo: 0.15
  pitch_magnitude_apex: 0.05
  lock_spine: true
  apex_height: -1
  speed: 1.5
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_work: 100
  mu: 1
  eps: 1e-2
  tol: 1
  file_name_out: bounding_gait6
  file_name_in: bounding_gait5
- name: bound_7
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  pitch_magnitude_lo: 0.1
  pitch_magnitude_apex: 0.05
  lock_spine: true
  apex_height: -1
  speed: 2
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_work: 100
  mu: 1
  eps: 1e-2
  tol: 1e-2
  file_name_out: bounding_gait7
  file_name_in: bounding_gait6
- name: bound_8
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  pitch_magnitude_lo: 0.2
  pitch_magnitude_apex: 0.05
  lock_spine: false
  apex_height: -1
  speed: 2.5
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_work: 100
  mu: 0.7
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait8
  file_name_in: bounding_gait7
- name: bound_9
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  pitch_magnitude_lo: 0.4
  pitch_magnitude_apex: 0.05
  lock_spine: false
  apex_height: -1
  speed: 3
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_work: 100
  mu: 0.7
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait9
  file_name_in: bounding_gait8
- name: bound_10
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  pitch_magnitude_lo: 0.4
  pitch_magnitude_apex: 0.05
  lock_spine: false
  apex_height: -1
  speed: 3
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_work: 100
  mu: 0.7
  eps: 1e-2
  tol: 1e-2
  file_name_out: bounding_gait10
  file_name_in: bounding_gait9
- name: bound_11
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  pitch_magnitude_lo: 0.2
  pitch_magnitude_apex: 0.02
  lock_spine: false
  apex_height: -1
  speed: 3
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_work: 100
  mu: 0.7
  eps: 1e-2
  tol: 1e-2
  file_name_out: bounding_gait11
  file_name_in: bounding_gait10