- num_optimizations: 1
  initial_guess: ""
  saved_directory: /home/feng/Downloads/dairlib/examples/Spirit_spine/saved_trajectories/bound_gait/
  spine_type: twisting
  urdf_path: examples/Spirit_spine/spirit_with_spine_drake.urdf
  num_perturbations: 5
  mean: 0
  var: 0.01
  iterate:
    - name: bound_3
      num: 1
      iteration_variable: speed
      for:
        start: 0.1
        end: 2.5
        step_size: 0.2
    - name: bound_4
      iteration_variable: speed
      parallel_for:
        start: 0.1
        end: 2.5
        step_size: 0.2
    - name: bound_5
      iteration_variable: speed
      parallel_for:
        start: 0.1
        end: 2.5
        step_size: 0.2
    - name: bound_6
      iteration_variable: speed
      parallel_for:
        start: 0.1
        end: 2.5
        step_size: 0.2
- name: bound_1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.35
  time_symmetry: true
  pitch_magnitude_lo: 0.1
  pitch_magnitude_apex: 0.1
  lock_spine: true
  apex_height: 0.4
  speed: 0
  min_duration: 0.4
  max_duration: 1
  lock_leg_apex: true
  cost_actuation: 3
  cost_velocity: 10
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_power: 0
  mu: 100
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait1
  file_name_in: ""
- name: bound_3
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: true
  pitch_magnitude_lo: 0.2
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 0.1
  min_duration: 0.4
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 1
  cost_actuation_legs_flight: 0
  cost_time: 500
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait3_p1
  file_name_in: bounding_gait1
- name: bound_3
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: true
  pitch_magnitude_lo: 0.2
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 0.3
  min_duration: 0.4
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 1
  cost_actuation_legs_flight: 0
  cost_time: 500
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait3_p2
  file_name_in: bounding_gait3_p1
- name: bound_3
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: true
  pitch_magnitude_lo: 0.2
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 0.5
  min_duration: 0.4
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 1
  cost_actuation_legs_flight: 0
  cost_time: 500
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait3_p3
  file_name_in: bounding_gait3_p2
- name: bound_3
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: true
  pitch_magnitude_lo: 0.2
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 0.7
  min_duration: 0.4
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 1
  cost_actuation_legs_flight: 0
  cost_time: 500
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait3_p4
  file_name_in: bounding_gait3_p3
- name: bound_3
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: true
  pitch_magnitude_lo: 0.2
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 0.8999999999999999
  min_duration: 0.4
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 1
  cost_actuation_legs_flight: 0
  cost_time: 500
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait3_p5
  file_name_in: bounding_gait3_p4
- name: bound_3
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: true
  pitch_magnitude_lo: 0.2
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 1.1
  min_duration: 0.4
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 1
  cost_actuation_legs_flight: 0
  cost_time: 500
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait3_p6
  file_name_in: bounding_gait3_p5
- name: bound_3
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: true
  pitch_magnitude_lo: 0.2
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 1.3
  min_duration: 0.4
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 1
  cost_actuation_legs_flight: 0
  cost_time: 500
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait3_p7
  file_name_in: bounding_gait3_p6
- name: bound_3
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: true
  pitch_magnitude_lo: 0.2
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 1.5
  min_duration: 0.4
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 1
  cost_actuation_legs_flight: 0
  cost_time: 500
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait3_p8
  file_name_in: bounding_gait3_p7
- name: bound_3
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: true
  pitch_magnitude_lo: 0.2
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 1.7
  min_duration: 0.4
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 1
  cost_actuation_legs_flight: 0
  cost_time: 500
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait3_p9
  file_name_in: bounding_gait3_p8
- name: bound_3
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: true
  pitch_magnitude_lo: 0.2
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 1.9
  min_duration: 0.4
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 1
  cost_actuation_legs_flight: 0
  cost_time: 500
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait3_p10
  file_name_in: bounding_gait3_p9
- name: bound_3
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: true
  pitch_magnitude_lo: 0.2
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 2.1
  min_duration: 0.4
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 1
  cost_actuation_legs_flight: 0
  cost_time: 500
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait3_p11
  file_name_in: bounding_gait3_p10
- name: bound_3
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: true
  pitch_magnitude_lo: 0.2
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 2.3
  min_duration: 0.4
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 1
  cost_actuation_legs_flight: 0
  cost_time: 500
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait3
  file_name_in: bounding_gait3_p11
- name: bound_4
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: false
  pitch_magnitude_lo: 0.5
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 0.1
  min_duration: 0.3
  max_duration: 0.8
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait4_p1
  file_name_in: bounding_gait3_p1
- name: bound_4
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: false
  pitch_magnitude_lo: 0.5
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 0.3
  min_duration: 0.3
  max_duration: 0.8
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait4_p2
  file_name_in: bounding_gait3_p2
- name: bound_4
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: false
  pitch_magnitude_lo: 0.5
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 0.5
  min_duration: 0.3
  max_duration: 0.8
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait4_p3
  file_name_in: bounding_gait3_p3
- name: bound_4
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: false
  pitch_magnitude_lo: 0.5
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 0.7
  min_duration: 0.3
  max_duration: 0.8
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait4_p4
  file_name_in: bounding_gait3_p4
- name: bound_4
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: false
  pitch_magnitude_lo: 0.5
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 0.8999999999999999
  min_duration: 0.3
  max_duration: 0.8
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait4_p5
  file_name_in: bounding_gait3_p5
- name: bound_4
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: false
  pitch_magnitude_lo: 0.5
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 1.1
  min_duration: 0.3
  max_duration: 0.8
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait4_p6
  file_name_in: bounding_gait3_p6
- name: bound_4
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: false
  pitch_magnitude_lo: 0.5
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 1.3
  min_duration: 0.3
  max_duration: 0.8
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait4_p7
  file_name_in: bounding_gait3_p7
- name: bound_4
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: false
  pitch_magnitude_lo: 0.5
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 1.5
  min_duration: 0.3
  max_duration: 0.8
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait4_p8
  file_name_in: bounding_gait3_p8
- name: bound_4
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: false
  pitch_magnitude_lo: 0.5
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 1.7
  min_duration: 0.3
  max_duration: 0.8
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait4_p9
  file_name_in: bounding_gait3_p9
- name: bound_4
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: false
  pitch_magnitude_lo: 0.5
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 1.9
  min_duration: 0.3
  max_duration: 0.8
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait4_p10
  file_name_in: bounding_gait3_p10
- name: bound_4
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: false
  pitch_magnitude_lo: 0.5
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 2.1
  min_duration: 0.3
  max_duration: 0.8
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait4_p11
  file_name_in: bounding_gait3_p11
- name: bound_4
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  time_symmetry: false
  pitch_magnitude_lo: 0.5
  pitch_magnitude_apex: 0.2
  lock_spine: true
  apex_height: -1
  speed: 2.3
  min_duration: 0.3
  max_duration: 0.8
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: bounding_gait4
  file_name_in: bounding_gait3