- num_optimizations: 1
  initial_guess: ""
  saved_directory: /home/feng/Downloads/dairlib/examples/Spirit_spine/saved_trajectories/turn/
  spine_type: twisting
  urdf_path: examples/Spirit_spine/spirit_with_spine_drake.urdf
  num_perturbations: 5
  mean: 0
  var: 0.01
- name: turn_7
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
  initial_height: 0.2
  pitch_magnitude_lo: 0.1
  pitch_magnitude_apex: 0.05
  orientation_diff: 0.3
  lock_spine: true
  apex_height: -1
  speed: 2
  max_duration: 1
  lock_leg_apex: false
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 0
  cost_actuation_legs_flight: 0
  cost_time: 0
  cost_power: 100
  mu: 1
  eps: 1e-2
  tol: 1e-1
  file_name_out: turn7
  file_name_in: bounding_gait7