# YAML spirit parkour jump configuration
-
  num_optimizations: 2
  initial_guess: ""  #if it is empty, the program will generate initial guess. Otherwise, we use the file given here as the initial guess
  saved_directory: /home/feng/Downloads/dairlib/examples/Spirit/saved_trajectories/parkour_jump_test1/
  iterate:
    


- 
  name: parkour_pronk_1
  n_jumps: 2
  transition_surface:
    - 0
    - 1
  initial_stand:
    - 0  #normal x
    - 0  #normal y
    - 1  #normal z
    - 0  #offset x
    - 0  #offset y
    - 0  #offset z
    - false #rerun
  final_stand:
    - 0  #normal x
    - 0  #normal y
    - 1  #normal z
    - 0  #offset x
    - 0  #offset y
    - 0 #offset z
    - false #rerun
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 7
  apex_height: 0.65
  max_pitch_magnitude: 0.6
  max_apex_pitch_magnitude: 0.1
  lock_rotation: true
  lock_legs_apex: false
  force_symmetry: true
  max_duration: 4
  cost_actuation: 3
  cost_velocity: 10 
  cost_velocity_legs_flight: 2 
  cost_actuation_legs_flight: 1 
  cost_work: 0 
  mu: 100
  eps: 5e-2
  tol: 1e-1
  work_constraint_scale: 0
  file_name_out: simple_parkour_2_1
  file_name_in: ""
  animate: false
  
# - 
#   name: parkour_pronk_2
#   n_jumps: 2
#   transition_surface:
#     - 0.01 #offset x
#     - 1     #normal z
#   initial_stand:
#     - 0  #normal x
#     - 0  #normal y
#     - 1  #normal z
#     - 0  #offset x
#     - 0  #offset y
#     - 0  #offset z
#     - false #rerun
#   final_stand:
#     - 0  #normal x
#     - 0  #normal y
#     - 1  #normal z
#     - 0.02  #offset x
#     - 0  #offset y
#     - 0 #offset z
#     - false #rerun
#   stand_height: 0.23
#   nKnotpoints_flight: 7
#   nKnotpoints_stances: 7
#   apex_height: 0.45
#   max_pitch_magnitude: 1
#   max_apex_pitch_magnitude: 0.3
#   lock_rotation: true
#   lock_legs_apex: false
#   force_symmetry: true
#   max_duration: 2
#   cost_actuation: 3
#   cost_velocity: 15 
#   cost_velocity_legs_flight: 2 
#   cost_actuation_legs_flight: 1 
#   cost_work: 0 
#   mu: 100
#   eps: 1e-2
#   tol: 1e-1
#   work_constraint_scale: 0
#   file_name_out: simple_parkour_2_2
#   file_name_in: simple_parkour_2_1
#   animate: true