# YAML spirit jump configuration
-
  num_optimizations: 4
  initial_guess: ""  #if it is empty, the program will generate initial guess. Otherwise, we use the file given here as the initial guess
  saved_directory: /home/feng/Downloads/dairlib/examples/Spirit_spine/saved_trajectories/bound_test1/
  spine_type: twisting
  urdf_path: examples/Spirit_spine/spirit_with_spine_drake.urdf
  num_perturbations: 5
  mean: 1
  var: 0.1
- 
  name: bound_1
  ipopt: true
  num_knot_points:
    - 4
    - 4
    - 7
    - 7
    - 4
    - 4
  initial_height: 0.2
  pitch_magnitude_lo: 0.6
  pitch_magnitude_apex: 0.1
  apex_height: 0.45
  fore_aft_displacement: 0
  max_duration: 1.8
  cost_actuation: 3
  cost_velocity: 10 
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0 
  mu: 100
  eps: 1e-3
  tol: 1e-2
  file_name_out: in_place_bound
  file_name_in: ""
  
-
  name: bound_2
  ipopt: true
  num_knot_points:
    - 4
    - 4
    - 7
    - 7
    - 4
    - 4
  initial_height: 0.2
  pitch_magnitude_lo: 1.0
  pitch_magnitude_apex: 0.3
  apex_height: 0.45
  fore_aft_displacement: 1.0
  max_duration: 1.8
  cost_actuation: 3
  cost_velocity: 10 
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0 
  mu: 10
  eps: 1e-3
  tol: 1e-0
  file_name_out: bound_100cm
  file_name_in: in_place_bound
 
-
  name: bound_3
  ipopt: true
  num_knot_points:
    - 4
    - 4
    - 7
    - 7
    - 4
    - 4
  initial_height: 0.2
  pitch_magnitude_lo: 1
  pitch_magnitude_apex: 0.3
  apex_height: 0.45
  fore_aft_displacement: 1
  max_duration: 1.8
  cost_actuation: 3
  cost_velocity: 10 
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0 
  mu: 1
  eps: 1e-3
  tol: 1e-0
  file_name_out: bound_100cm_low_mu
  file_name_in: bound_100cm

-
  name: bound_4
  ipopt: true
  num_knot_points:
    - 4
    - 4
    - 7
    - 7
    - 4
    - 4
  initial_height: 0.2
  pitch_magnitude_lo: 1
  pitch_magnitude_apex: 0.3
  apex_height: 0.45
  fore_aft_displacement: 1
  max_duration: 1.8
  cost_actuation: 0.03
  cost_velocity: 0.1
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 0
  cost_work: 100 
  mu: 1
  eps: 1e-2
  tol: 2e-1
  file_name_out: bound_100cm_min_work
  file_name_in: bound_100cm_low_mu
