# YAML spirit parkour jump configuration
-
  num_optimizations: 2
  initial_guess: ""  #if it is empty, the program will generate initial guess. Otherwise, we use the file given here as the initial guess
  spine_type: twisting
  urdf_path: examples/Spirit_spine/spirit_with_spine_drake.urdf
  saved_directory: examples/Spirit_spine/saved_trajectories/parkour_test/
  data_directory: examples/Spirit_spine/data/parkour/test/
  num_perturbations: 1
  mean: 1
  var: 0.000001
  iterate:
    -
      name: parkour_pronk_7
      num: 1
      iteration_variable: fore_aft_displacement
      for:
        start: 0.6
        end: 2.2
        step_size: 0.1
    -
      name: parkour_pronk_8
      iteration_variable: fore_aft_displacement
      num: 2
      for:
        start: 0.6
        end: 2.2
        step_size: 0.1

- 
  name: parkour_pronk_1
  n_jumps: 2
  transition_surface:
    - 
      - 0     #normal x
      - 0     #normal y
      - 1     #normal z
      - 0     #offset x
      - 0     #offset y
      - 0.3     #offset z
  initial_stand:
    - 0  #normal x
    - 0  #normal y
    - 1  #normal z
    - 0  #offset x
    - 0  #offset y
    - 0  #offset z
    - false #rerun
  final_stand:
    - 0  #normal x
    - 0  #normal y
    - 1  #normal z
    - 0  #offset x
    - 0  #offset y
    - 0 #offset z
    - false #rerun
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 4
  apex_heights: 
    - 0.7
    - 0.7
  max_pitch_magnitude: 0.6
  max_apex_pitch_magnitude: 0.1
  pose_ref: true
  roll_ref: 0.3
  yaw_ref: 0.1
  pitch_ref: 0.3
  max_duration: 4
  cost_actuation: 3
  cost_velocity: 10 
  cost_velocity_legs_flight: 2 
  cost_actuation_legs_flight: 1 
  cost_time: 1000
  cost_work: 0 
  mu: 100
  eps: 5e-2
  tol: 1e-1
  xtol: 1e-2
  file_name_out: parkour1
  file_name_in: ""
  


- 
  name: parkour_pronk_2
  n_jumps: 2
  transition_surface:
    - 
      - 0     #normal x
      - 0.4     #normal y
      - 0.8     #normal z
      - 0     #offset x
      - -0.1     #offset y
      - 0.25    #offset z
  initial_stand:
    - 0  #normal x
    - 0  #normal y
    - 1  #normal z
    - 0  #offset x
    - 0  #offset y
    - 0  #offset z
    - false #rerun
  final_stand:
    - 0  #normal x
    - 0  #normal y
    - 1  #normal z
    - 0  #offset x
    - 0  #offset y
    - 0 #offset z
    - false #rerun
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 4
  apex_heights: 
    - 0.65
    - 0.65
  max_pitch_magnitude: 0.6
  max_apex_pitch_magnitude: 0.1
  pose_ref: true
  roll_ref: 0.2
  yaw_ref: 0.1
  pitch_ref: 0.1
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10 
  cost_velocity_legs_flight: 2 
  cost_actuation_legs_flight: 1 
  cost_time: 1000
  cost_work: 0 
  mu: 100
  eps: 1e-2
  tol: 1e-1
  xtol: 1e-2
  file_name_out: parkour2
  file_name_in: parkour1


- 
  name: parkour_pronk_3
  n_jumps: 2
  transition_surface:
    - 
      - 0     #normal x
      - 0.8     #normal y
      - 0.3     #normal z
      - 0     #offset x
      - -0.2     #offset y
      - 0.25    #offset z
  initial_stand:
    - 0  #normal x
    - 0  #normal y
    - 1  #normal z
    - 0  #offset x
    - 0  #offset y
    - 0  #offset z
    - false #rerun
  final_stand:
    - 0  #normal x
    - 0  #normal y
    - 1  #normal z
    - 0  #offset x
    - 0  #offset y
    - 0 #offset z
    - false #rerun
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 4
  apex_heights: 
    - 0.65
    - 0.65
  max_pitch_magnitude: 0.6
  max_apex_pitch_magnitude: 0.1
  pose_ref: true
  roll_ref: 0.3
  yaw_ref: 0.1
  pitch_ref: 0.3
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10 
  cost_velocity_legs_flight: 2 
  cost_actuation_legs_flight: 1 
  cost_time: 1000
  cost_work: 0 
  mu: 10
  eps: 1e-2
  tol: 1e-1
  xtol: 1e-2
  file_name_out: parkour3
  file_name_in: parkour2

- 
  name: parkour_pronk_4
  n_jumps: 2
  transition_surface:
    - 
      - 0     #normal x
      - 0.8     #normal y
      - 0.3     #normal z
      - 0.3     #offset x
      - -0.2     #offset y
      - 0.25    #offset z
  initial_stand:
    - 0  #normal x
    - 0  #normal y
    - 1  #normal z
    - 0  #offset x
    - 0  #offset y
    - 0  #offset z
    - false #rerun
  final_stand:
    - 0  #normal x
    - 0  #normal y
    - 1  #normal z
    - 0.6  #offset x
    - 0  #offset y
    - 0 #offset z
    - false #rerun
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 4
  apex_heights: 
    - 0.65
    - 0.65
  max_pitch_magnitude: 0.6
  max_apex_pitch_magnitude: 0.1
  pose_ref: true
  roll_ref: 1
  yaw_ref: 0.5
  pitch_ref: 0.6
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10 
  cost_velocity_legs_flight: 2 
  cost_actuation_legs_flight: 1 
  cost_time: 1000
  cost_work: 0 
  mu: 10
  eps: 1e-2
  tol: 1e0
  xtol: 1e-2
  file_name_out: parkour4
  file_name_in: parkour3
  
- 
  name: parkour_pronk_5
  n_jumps: 2
  transition_surface:
    - 
      - 0     #normal x
      - 1     #normal y
      - 0     #normal z
      - 0.3     #offset x
      - -0.45     #offset y
      - 0.35    #offset z
  initial_stand:
    - 0  #normal x
    - 0  #normal y
    - 1  #normal z
    - 0  #offset x
    - 0  #offset y
    - 0  #offset z
    - false #rerun
  final_stand:
    - 0  #normal x
    - 0  #normal y
    - 1  #normal z
    - 0.6  #offset x
    - 0.05  #offset y
    - 0 #offset z
    - false #rerun
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 4
  apex_heights: 
    - 0.4
    - 0.4
  max_pitch_magnitude: 1.2
  max_apex_pitch_magnitude: 0.1
  pose_ref: true
  roll_ref: 0.5
  yaw_ref: 0.5
  pitch_ref: 0.4
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10 
  cost_velocity_legs_flight: 15 
  cost_actuation_legs_flight: 1 
  cost_time: 1000
  cost_work: 0
  mu: 10
  eps: 1e-2
  tol: 1e-1
  xtol: 5e-2
  file_name_out: parkour5
  file_name_in: parkour4

- 
  name: parkour_pronk_6
  warm_up: false
  n_jumps: 2
  transition_surface:
    - 
      - 0     #normal x
      - 1     #normal y
      - 0     #normal z
      - 0.3     #offset x
      - -0.6     #offset y
      - 0.4    #offset z
  initial_stand:
    - 0  #normal x
    - 0  #normal y
    - 1  #normal z
    - 0  #offset x
    - 0  #offset y
    - 0  #offset z
    - false #rerun
  final_stand:
    - 0  #normal x
    - 0  #normal y
    - 1  #normal z
    - 0.6  #offset x
    - 0  #offset y
    - 0 #offset z
    - false #rerun
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 4
  apex_heights: 
    - 0.4
    - 0.4
  max_pitch_magnitude: 1.2
  max_apex_pitch_magnitude: 0.1
  pose_ref: true
  roll_ref: 1.2
  yaw_ref: 0.5
  pitch_ref: 0.7
  max_duration: 2
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 10
  cost_actuation_legs_flight: 15
  cost_time: 0
  cost_work: 100
  mu: 3
  eps: 1e-2
  tol: 1e-1
  xtol: 5e-2
  file_name_out: parkour6
  file_name_in: parkour5
- 
  name: parkour_pronk_7
  warm_up: true
  n_jumps: 2
  initial_stand:
    - 0  #normal x
    - 0  #normal y
    - 1  #normal z
    - 0  #offset x
    - 0  #offset y
    - 0  #offset z
    - false #rerun
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 4
  lock_leg_flight: true
  apex_heights: 
    - 0.4
    - 0.4
  pose_ref: true
  roll_ref: 1.6
  yaw_ref: 0.8
  pitch_ref: 1
  max_duration: 2.5
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 10
  cost_actuation_legs_flight: 1
  cost_time: 0
  cost_work: 100
  mu: 0.8
  eps: 1e-2
  tol: 1e-1
  xtol: 1e-1
  ytol: 5e-2
  file_name_out: parkour7
  file_name_in: parkour6
- 
  name: parkour_pronk_8
  warm_up: true
  n_jumps: 2
  initial_stand:
    - 0  #normal x
    - 0  #normal y
    - 1  #normal z
    - 0  #offset x
    - 0  #offset y
    - 0  #offset z
    - false #rerun
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 4
  apex_heights: 
    - 0.4
    - 0.4
  lock_leg_flight: true
  pose_ref: true
  roll_ref: 1.6
  yaw_ref: 0.8
  pitch_ref: 1
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 5
  cost_actuation_legs_flight: 2 
  cost_time: 0
  cost_work: 100
  mu: 0.8
  eps: 1e-2
  tol: 3e-1
  xtol: 2e-1
  ytol: 3e-1
  ztol: 3e-1
  file_name_out: parkour8
  file_name_in: parkour7
- 
  name: parkour_pronk_9
  warm_up: true
  n_jumps: 2
  initial_stand:
    - 0  #normal x
    - 0  #normal y
    - 1  #normal z
    - 0  #offset x
    - 0  #offset y
    - 0  #offset z
    - false #rerun
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 4
  apex_heights: 
    - 0.4
    - 0.4
  lock_leg_flight: true
  pose_ref: true
  roll_ref: 1.6
  yaw_ref: 0.7
  pitch_ref: 1
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 0 
  cost_time: 0
  cost_work: 100
  mu: 0.8
  eps: 1e-2
  tol: 3e-2
  xtol: 2e-1
  ytol: 3e-1
  ztol: 3e-1
  file_name_out: parkour9
  file_name_in: parkour8