- num_optimizations: 4
  initial_guess: ""
  saved_directory: /home/feng/Downloads/dairlib/examples/Spirit_spine/saved_trajectories/jump_test1/
  spine_type: twisting
  urdf_path: examples/Spirit_spine/spirit_with_spine_drake.urdf
  iterate:
    name: jump_4
    iteration_variable: fore_aft_displacement
    for:
      start: 0.3
      end: 1.5
      step_size: 0.05
- name: jump_1
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0
  lock_rotation: true
  lock_legs_apex: true
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10
  cost_work: 0
  cost_time: 0
  mu: 100
  eps: 1e-2
  tol: 1e-1
  file_name_out: simple_jump
  file_name_in: ""
- name: jump_2
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0.3
  lock_rotation: true
  lock_legs_apex: true
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10
  cost_work: 0
  cost_time: 0
  mu: 100
  eps: 0
  tol: 1e-2
  file_name_out: jump_100cm
  file_name_in: ""
- name: jump_3
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0.3
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10
  cost_work: 0
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq
  file_name_in: jump_100cm
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0.3
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_0
  file_name_in: jump_100cm_hq
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0.35
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_1
  file_name_in: jump_100cm_hq_0
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0.4
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_2
  file_name_in: jump_100cm_hq_1
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0.45
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_3
  file_name_in: jump_100cm_hq_2
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0.4999999999999999
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_4
  file_name_in: jump_100cm_hq_3
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0.5499999999999999
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_5
  file_name_in: jump_100cm_hq_4
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0.6
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_6
  file_name_in: jump_100cm_hq_5
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0.65
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_7
  file_name_in: jump_100cm_hq_6
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0.7000000000000001
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_8
  file_name_in: jump_100cm_hq_7
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0.7500000000000001
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_9
  file_name_in: jump_100cm_hq_8
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0.8000000000000002
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_10
  file_name_in: jump_100cm_hq_9
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0.8500000000000002
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_11
  file_name_in: jump_100cm_hq_10
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0.9000000000000002
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_12
  file_name_in: jump_100cm_hq_11
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0.9500000000000003
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_13
  file_name_in: jump_100cm_hq_12
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 1
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_14
  file_name_in: jump_100cm_hq_13
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 1.05
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_15
  file_name_in: jump_100cm_hq_14
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 1.1
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_16
  file_name_in: jump_100cm_hq_15
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 1.15
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_17
  file_name_in: jump_100cm_hq_16
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 1.2
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_18
  file_name_in: jump_100cm_hq_17
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 1.25
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_19
  file_name_in: jump_100cm_hq_18
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 1.3
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_20
  file_name_in: jump_100cm_hq_19
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 1.350000000000001
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_21
  file_name_in: jump_100cm_hq_20
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 1.400000000000001
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_22
  file_name_in: jump_100cm_hq_21
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 1.450000000000001
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0
  cost_velocity: 0
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_work_option3
  file_name_in: jump_100cm_hq_22