- num_optimizations: 4
  initial_guess: ""
  saved_directory: /home/feng/Downloads/dairlib/examples/Spirit_spine/saved_trajectories/jump_test1/
- name: jump_1
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 0
  lock_rotation: true
  lock_legs_apex: true
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10
  cost_work: 0
  cost_time: 0
  mu: 100
  eps: 1e-2
  tol: 1e-1
  file_name_out: simple_jump
  file_name_in: ""
- name: jump_2
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 1
  lock_rotation: true
  lock_legs_apex: true
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10
  cost_work: 0
  cost_time: 0
  mu: 100
  eps: 0
  tol: 1e-2
  file_name_out: jump_100cm
  file_name_in: ""
- name: jump_3
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 1
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10
  cost_work: 0
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq
  file_name_in: jump_100cm
- name: jump_4
  duration: 1
  ipopt: true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.45
  initial_height: 0.2
  fore_aft_displacement: 1
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 1.5
  cost_actuation: 0.3
  cost_velocity: 1
  cost_work: 100
  cost_time: 0
  mu: 1
  eps: 1e-2
  tol: 1e-3
  file_name_out: jump_100cm_hq_work_option3
  file_name_in: jump_100cm_hq