- num_optimizations: 4
  initial_guess: ""
  saved_directory: /home/feng/Downloads/dairlib/examples/Spirit/saved_trajectories/box_jump_test1/
  iterate:
    name: box_jump_3
    iteration_variable: final_stand
    values:
      -
        - 0
        - 0
        - 1
        - 1
        - 0
        - 0.3
        - false
- name: box_jump_1
  stand_height: 0.23
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 1
    - 0
    - 0.3
    - false
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.7
  initial_height: 0.23
  fore_aft_displacement: 0
  lock_rotation: true
  lock_legs_apex: true
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10
  cost_work: 0
  mu: 100
  eps: 1e-2
  tol: 1e-1
  work_constraint_scale: 0
  file_name_out: simple_boxjump
  file_name_in: ""
  animate: false
- name: box_jump_2
  stand_height: 0.23
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 1
    - 0
    - 0.3
    - true
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.7
  initial_height: 0.23
  fore_aft_displacement: 1
  lock_rotation: true
  lock_legs_apex: true
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10
  cost_work: 0
  mu: 100
  eps: 0
  tol: 1e-2
  work_constraint_scale: 0
  file_name_out: boxjump_iterativeBox45_0
  file_name_in: ""
  animate: false
- name: box_jump_3
  stand_height: 0.23
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 1
    - 0
    - 0.3
    - false
  num_knot_points:
    - 7
    - 7
    - 7
    - 7
  apex_height: 0.7
  initial_height: 0.23
  fore_aft_displacement: 1
  lock_rotation: false
  lock_legs_apex: false
  force_symmetry: false
  use_nominal_stand: true
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 10
  cost_work: 0
  mu: 1.5
  eps: 1e-2
  tol: 1e-6
  work_constraint_scale: 0
  file_name_out: boxjump_iterativeBox45_1
  file_name_in: boxjump_iterativeBox45_0
  animate: true