- initial_guess: ""
  saved_directory: /home/feng/Downloads/dairlib/examples/Spirit_spine/saved_trajectories/parkour_3wall_test1/
  iterate: ~
- name: parkour_wall_1
  n_jumps: 3
  transition_surface:
    -
      - 0
      - 0
      - 1
      - 0
      - 0
      - 0
    -
      - 0
      - 0
      - 1
      - 0
      - 0
      - 0
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 7
  apex_heights:
    - 0.7
    - 0.7
    - 0.7
  max_pitch_magnitude: 0.6
  max_apex_pitch_magnitude: 0.1
  lock_rotation: true
  lock_legs_apex: false
  force_symmetry: true
  max_duration: 4
  cost_actuation: 3
  cost_velocity: 10
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0
  mu: 100
  eps: 5e-2
  tol: 1
  xtol: 1e-2
  work_constraint_scale: 0
  file_name_out: simple_parkour_2_1
  file_name_in: ""
  animate: false
- name: parkour_wall_2
  n_jumps: 3
  transition_surface:
    -
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    -
      - 0
      - 0
      - 1
      - 2
      - 0
      - 0
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 3
    - 0
    - 0
    - false
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 7
  apex_heights:
    - 0.65
    - 0.65
    - 0.65
  max_pitch_magnitude: 1
  max_apex_pitch_magnitude: 0.3
  lock_rotation: true
  lock_legs_apex: false
  force_symmetry: true
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 15
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0
  mu: 100
  eps: 1e-2
  tol: 1
  xtol: 5e-2
  work_constraint_scale: 0
  file_name_out: simple_parkour_2_2
  file_name_in: simple_parkour_2_1
  animate: false
- name: parkour_wall_3
  n_jumps: 3
  transition_surface:
    -
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0.25
    -
      - 0
      - 0
      - 1
      - 2
      - 0
      - 0.25
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 3
    - 0
    - 0
    - false
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 7
  apex_heights:
    - 0.65
    - 0.65
    - 0.65
  max_pitch_magnitude: 1
  max_apex_pitch_magnitude: 0.3
  lock_rotation: true
  lock_legs_apex: false
  force_symmetry: true
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 15
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0
  mu: 100
  eps: 1e-2
  tol: 1e-1
  xtol: 5e-2
  work_constraint_scale: 0
  file_name_out: simple_parkour_2_3
  file_name_in: simple_parkour_2_2
  animate: false
- name: parkour_wall_4
  n_jumps: 3
  transition_surface:
    -
      - 0
      - 0.2
      - 0.5
      - 1
      - -0.1
      - 0.25
    -
      - 0
      - -0.2
      - 0.5
      - 2
      - 0.1
      - 0.25
  initial_stand:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - false
  final_stand:
    - 0
    - 0
    - 1
    - 3
    - 0
    - 0
    - false
  stand_height: 0.23
  nKnotpoints_flight: 7
  nKnotpoints_stances: 7
  apex_heights:
    - 0.65
    - 0.65
    - 0.65
  max_pitch_magnitude: 1
  max_apex_pitch_magnitude: 0.3
  lock_rotation: true
  lock_legs_apex: false
  force_symmetry: true
  max_duration: 2
  cost_actuation: 3
  cost_velocity: 15
  cost_velocity_legs_flight: 2
  cost_actuation_legs_flight: 1
  cost_time: 1000
  cost_work: 0
  mu: 100
  eps: 1e-2
  tol: 1e-1
  xtol: 5e-2
  work_constraint_scale: 0
  file_name_out: simple_parkour_2_4
  file_name_in: simple_parkour_2_3
  animate: false